# Adapted from: https://github.com/elifesciences/builder-base-formula/blob/master/elife/config/etc-elasticsearch-elasticsearch.yml
# Elasticsearch configuration for {{ grains['fqdn'] }}

node.name: "{{ salt['elife.cfg']('project.stackname') }}"
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
network.host: 127.0.0.1,{{ salt['elife.cfg']('cfn.outputs.PrivateIP1') }}
