# Elasticsearch configuration for {{ grains['fqdn'] }}

# master config file:
# - https://github.com/elastic/elasticsearch/blob/master/distribution/src/config/elasticsearch.yml
# master config file for 2.4 (this version):
# - https://github.com/elastic/elasticsearch/blob/2.4/distribution/src/main/resources/config/elasticsearch.yml

node.name: "{{ salt['elife.cfg']('project.stackname') }}"
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
{% if salt['elife.cfg']('cfn.outputs.PrivateIP1') %}
network.host: 127.0.0.1,{{ salt['elife.cfg']('cfn.outputs.PrivateIP1') }}
{% else %}
network.host: 127.0.0.1
{% endif %}

# snapshot REPOsitory
path.repo: ["/var/lib/elasticsearch/repo"]
path.logs: /var/log/elasticsearch
path.data: /var/lib/elasticsearch
