# Adapted from: https://github.com/elifesciences/builder-base-formula/blob/master/elife/config/etc-elasticsearch-elasticsearch.yml
# Elasticsearch configuration for {{ grains['fqdn'] }}

node.name: "{{ grains['fqdn'] }}"
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
